default_url_options:
  protcol: 'https'
  host: 'ff14matching.com'

sorcery:
  google_callback_url: 'https://www.ff14matching.com/oauth/callback?provider=google'

Sorcery:
  line_callback_url: 'https://www.ff14matching.com/oauth/callback?provider=line'